package com.startpage.dto;

public class LoginDto {
	
//	USERNO NUMBER NOT NULL,
//	USERID VARCHAR2(500) NOT NULL,
//	USERPW VARCHAR2(500) NOT NULL,
//	USERNAME VARCHAR2(1000) NOT NULL,
//	USERADDR VARCHAR2(4000) NOT NULL,
//	USERPHONE VARCHAR2(4000) NOT NULL,
//	USEREMAIL VARCHAR2(100) NOT NULL,
//	USERENABLED VARCHAR2(2) NOT NULL,
//	USERROLE VARCHAR2(50) NOT NULL,
//	USERFOLLOWER NUMBER NOT NULL,
//	USERFOLLOWING NUMBER NOT NULL
	
}
