/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-09 11:26:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>메인페이지</title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t#s0{ float: left; width: 34% }\r\n");
      out.write("\t#s1{ float: left; width: 33%; padding: 25px 0px 25px 0px; }\r\n");
      out.write("\t#s2{ float: left; width: 100%; height: 50px;}\r\n");
      out.write("\t#s4{ padding: 8px 0px 0px 0px;\r\n");
      out.write("\t margin-left: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#ask1{ \r\n");
      out.write("\tborder: 2px solid black;\r\n");
      out.write("\tbackground-color: #fffbc1; \r\n");
      out.write("\tfont-weight: bold; \r\n");
      out.write("\tcolor: #3f385a;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("   <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.poptrox.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/skel.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<header style=\"height: 100px\">\r\n");
      out.write("\t\t\t\t<div id=\"s0\">\r\n");
      out.write("\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"WYW_날씨를 입다\" src=\"images/logo/logo_wyw_yellow.png\" width=\"200\" height=\"100\" onclick=\"location.href='mainController.do?command=mainpage'\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"s1\"><input type=\"text\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"s1\">\r\n");
      out.write("\t\t\t\t\t<input id=\"ask1\" type=\"button\" value=\"검색\" onclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"label\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/setting.png\" alt=\"setting\" align=\"right\" width=\"30px\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/user.png\" alt=\"user\" align=\"right\" width=\"30px\" onclick=\"location.href='mainController.do?command=mypage'\">\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/up.png\" alt=\"upload\" align=\"right\" width=\"30px\" onclick=\"location.href='mainController.do?command=StoryPage'\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t<section id=\"main\">\r\n");
      out.write("\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"weatherimg\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"city\">\r\n");
      out.write("\t\t\t\t\t\t\t<option hidden>현재 계신 도시를 선택해주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"seoul\">서울특별시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"incheon\">인천광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daejeon\">대전광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gwangju\">광주광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daegu\">대구광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ulsan\">울산광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"busan\">부산광역시</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gyeonggi-do\">경기도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gangwon-do\">강원도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"chungcheongbuk-do\">충청북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"chungcheongnam-do\">충청남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jeollabuk-do\">전라북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jeollanam-do\">전라남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gyeongsangbuk-do\">경상북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gyeongsangnam-do\">경상남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jeju-do\">제주도</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"weather\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"weatherDetail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"location\">현재 위치 : </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"current-temp\">현재 기온 : </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"feels-like\">체감 온도 : </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"current-time\">현재 시간 : </p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"icon\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"recommend\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"circle\" id=\"one\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"추천스토리1\" src=\"images/thumbs/01.jpg\" onclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"circle\" id=\"two\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"추천스토리2\" src=\"images/thumbs/02.jpg\" onclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"circle\" id=\"three\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"추천스토리3\" src=\"images/thumbs/03.jpg\" onclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"follower\">\r\n");
      out.write("\t\t\t\t\t\t<span>스토리 세로 배치 / 클릭 시 해당 페이지로</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t<p>&copy; Untitled. All rights reserved. Design: <a href=\"http://templated.co\">TEMPLATED</a>. Demo Images: <a href=\"http://unsplash.com\">Unsplash</a>.</p>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
