/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-09 11:15:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mvc.dto.UserDataDto;
import java.util.List;

public final class mysearch_005fres_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mvc.dto.UserDataDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("    \r\n");
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>MyPage</title>\r\n");
      out.write("<Style type=\"text/css\">\r\n");
      out.write("\t#s0{ float: left; width: 34% }\r\n");
      out.write("\t#s1{ float: left; width: 33%; padding: 30px 0px 25px 0px; margin-top:13px;}\r\n");
      out.write("\t#s4{ padding: 8px 0px 0px 0px;\r\n");
      out.write("\t\t margin-left: 25px;\r\n");
      out.write("\t\t}\t\t\t\r\n");
      out.write("/*main*/\t\t\r\n");
      out.write("\t.thumbnails {margin-top: 100px;}\t\r\n");
      out.write("\t#top>p {\r\n");
      out.write("\tmargin-top: 100px;\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tfont-size: 28pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("option {\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#middle {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".space {\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr>th {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 11px;\r\n");
      out.write("\tfont-size: 14pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr>td {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 14pt;\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("</Style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery.poptrox.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tvar followbtn = document.getElementById('followbtn');\r\n");
      out.write("\t\tvar followingbtn = document.getElementById('followingbtn');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfollowbtn.style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("\t\tfollowbtn.onclick = function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 List<UserDataDto> list = (List<UserDataDto>)request.getAttribute("list"); 
      out.write("\r\n");
      out.write("\t<!-- Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header>\t\r\n");
      out.write("\t\t\t<div id=\"s0\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"WYW_날씨를 입다\" src=\"images/logo/logo_wyw_yellow.png\" width=\"200\" height=\"100\" onclick=\"location.href='mainController.do?command=mainpage'\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"s1\">&nbsp;</div>\r\n");
      out.write("\t\t\t<div id=\"s1\">\r\n");
      out.write("\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/setting.png\" alt=\"setting\" align=\"right\" width=\"30px\">\r\n");
      out.write("\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/user.png\" alt=\"user\" align=\"right\" width=\"30px\" onclick=\"location.href='mainController.do?command=mypage'\">\r\n");
      out.write("\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/up.png\" alt=\"upload\" align=\"right\" width=\"30px\">\r\n");
      out.write("\t\t\t\t<img id=\"s4\" class=\"icons\" src=\"images/icon/search.png\" alt=\"upload\" align=\"right\" width=\"30px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div id=\"s2\"></div><!-- 위쪽 div 와 아래쪽 div를 나누는 용도 -->\r\n");
      out.write("</header>\r\n");
      out.write("<br>\r\n");
      out.write("<!-- Main -->\r\n");
      out.write("\t<section id=\"topsection\">\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<p>회원 목록</p>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"mypageController.do\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"search\">\r\n");
      out.write("\t\t<div id=\"middle\" class=\"space\">&nbsp;</div>\r\n");
      out.write("\t\t<div id=\"middle\" style=\"width: 9%;\">\r\n");
      out.write("\t\t\t<select name=\"select\">\r\n");
      out.write("\t\t\t\t<option value=\"id\" selected>아이디</option>\r\n");
      out.write("\t\t\t\t<option value=\"name\">이름</option>\r\n");
      out.write("\t\t\t\t<option value=\"address\">위치</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"middle\" style=\"width: 21%; padding: 0px 5px;\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchid\" id=\"searchid\" placeholder=\"search\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"middle\" style=\"width: 10%;\">\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"searchbtn\" id=\"searchbtn\" value=\"검색\"\r\n");
      out.write("\t\t\t\tstyle=\"background-color: #FFFBC1; color: black; width: 120px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"middle\" class=\"space\">&nbsp;</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<col width=\"100\">\r\n");
      out.write("\t\t<col width=\"100\">\r\n");
      out.write("\t\t<col width=\"100\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>주소</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			for (UserDataDto dto : list) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(dto.getUserid());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(dto.getUsername());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(dto.getUseraddr());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<img id=\"followbtn\" alt=\"fbt\" src=\"images/icon/follow.png\" width=\"100px\">\r\n");
      out.write("\t\t\t\t<img id=\"followingbtn\" alt=\"fbt\" src=\"images/icon/following.png\" width=\"100px\"> \r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<p>&copy; Untitled. All rights reserved. Design: <a href=\"http://templated.co\">TEMPLATED</a>. Demo Images: <a href=\"http://unsplash.com\">Unsplash</a>.</p>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
